###########################################################################
#   File Name    : config.yml                                             #
# ----------------------------------------------------------------------- #
#   Title        :                                                        #
#   Revision     : V1.0                                                   #
#   Notes        :                                                        #
# ----------------------------------------------------------------------- #
#   Revision History:                                                     #
#     When             Who         Revision       Description of change   #
# -----------      -----------    ---------      ------------------------ #
#   2-15-2016      charlie_weng     V1.0          Created the program     #
#                                                                         #
###########################################################################

# General
nodeid     : node01

#debug logger level
logLevel   : INFO

# port for the ledmq server
port       : 9090
# host for the ledmq server
host       : 0.0.0.0

#socket max timeout
socketMaxTimeout : 240000
heartbeatInterval: 30000
packetsTimeout   : 5
pksRepeatCount   : 3

debug      : false
sysType    : standalone
#sysType   : multimach
nodeType   : master
#nodeType  : slave 
    
# Storage options
storage:
  db       : ssdb
  ip       : 127.0.0.1 
  port     : 8888 
  
# mqtt server  
mqserver: 
  type     : mqtt
  preTopic : ledmq
  user     : admin
  passwd   : '123456'  
  port     : 2883
  host     : 127.0.0.1

# RPC server 
rpcserver:
  ip       : 127.0.0.1
  port     : 6000

# monitor server 
httpserver : 
  host     : 127.0.0.1
  port     : 9080                 
  user     : admin
  passwd   : '123456'
  # ip白名单  
  whitelist: 
   - 0.0.0.0/0
   - ::ffff:127.0.0.1
    
# Logger Configuration
logger:
  appenders:
     -
      type       : console
      category   : console
     -    
      category   : log
      type       : file
      filename   : ./logs/ledmq.log
      maxLogSize : 104800
      backups    : 100
     #replaceConsole: true
  levels:
    log : INFO
   #log : ALL
    console: ALL

# Plugin Configuration
plugin:
  # install modules 
  modules:
   - login
   - set
   - get
   - update
   - reset
   - req
  # system use protocol exp:'./protocol/proto-tlv.js'
  protocol:
   -
    name : tlv  
    path : ./tlv/proto-tlv.js
    port : 9090
   -
    name : modbus  
    path : ./modbus/proto-tlv.js
    port : 9091  
     
# Permissioning
permission:
  # Only config or custom permissionHandler at the moment
  type: config
  options:
    # Path to the permissionFile. Can be json, js or yml
    path: ./tokens.yml
    # Amount of times nested cross-references will be loaded. Avoids endless loops
  commToken : '0123456789'  

